import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals/styles/globals.css";
import { ThemeProvider } from "@/globals/wrappers/theme-provider";
import Navbar from "@/components/common/navbar/Navbar";
import Footer from "@/components/common/footer/Footer";

const geistSans = localFont({
  src: "../globals/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../globals/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          {/* <main className="flex flex-col min-h-[100vh] justify-between">
            <div> */}
              {/* <Navbar /> */}
              {children}
            {/* </div>
            <Footer />
          </main> */}
        </ThemeProvider>
      </body>
    </html>
  );
}
