#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🚧✨ Preparing your code for greatness: formatting, linting, and building before commit 🚧✨'

# Check Prettier standards
npm run check-format ||
(
    echo '🚨 Oops! Code formatting is out of alignment. 🚨 
            Prettier check failed. Run `npm run format`, make the changes, and try committing again.'
    false;
)

# Check ESLint standards
npm run check-lint --max-warnings=0 ||
(
    echo '🛑 ESLint has flagged some issues. 🛑
            Please fix the errors listed above, make necessary changes, and try committing again.'
    false; 
)

# Check TypeScript standards
npm run check-types ||
(
    echo '⚠️ TypeScript type check failed! ⚠️
            Some type issues need attention before committing. Please review the errors and correct them.'
    false;
)

# Build the project
echo '🧐 Everything looks good so far... Let’s ensure it builds properly. 🧐'

npm run build ||
(
    echo '❌ Build process failed. ❌ 
            Please check the errors above and fix them before proceeding.'
    false;
)

# If everything passes... Now we can commit
echo '✅ All checks passed! Your code is ready for commit. Great job! ✅'
